production:
  ignore_errors:
    - ActiveRecord::RecordNotFound
    - ActionController::RoutingError
    - ActiveRecord::QueryCanceled
    - Rack::Timeout::RequestTimeoutException
    - Faraday::ConnectionFailed 
    - PackageURL::InvalidPackageURL
    - Faraday::SSLError
    - Rack::Timeout::RequestExpiryError
    - Faraday::TimeoutError