name: Upgrade Ruby

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  upgrade-ruby:
    name: Upgrade Ruby version
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to update .ruby-version and other files
      pull-requests: write # Needed to create pull requests with Ruby upgrades
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: andrew/ruby-upgrade-action@6e2fd3872e875dfd321273b515a4b61c12a11166
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}