name: Upgrade Ruby

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  upgrade-ruby:
    name: Upgrade Ruby version
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to update .ruby-version and other files
      pull-requests: write # Needed to create pull requests with Ruby upgrades
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          persist-credentials: false
      - uses: andrew/ruby-upgrade-action@8f9acc112701e4c401dafa7eee6f0d469ea410e1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}